### PR TITLE
chore(tslint): migrate to tslint 4.0

### LINKED ISSUE #157: Upgrade to tslint 4
It would be nice to upgrade the tslint version to v4.

### PR DESCRIPTION
**Pull request by mgechev**
Resolves #157

### CODE REVIEW

**Comment by mgechev** [comment]
Probably by the end of next week. First we have to introduce support for external templates.

**Comment by maxime1992** [comment]
Any update about the release ? :)

**Comment by dominique-mueller** [comment]
Can't wait either, love this project!

**Comment by mgechev** [comment]
The release is planned for tomorrow, hopefully I won't get too many 🍻 tonight!

**Comment by maxime1992** [comment]
And here we go !!

image

It seems you managed your :beers: well ! Thanks @mgechev !! :smile:

**Pull request merged**
