### PR TITLE
feat: introduce support for Angular version 5

### PR DESCRIPTION
**Pull request by mgechev**
Fix https://github.com/mgechev/codelyzer/issues/409

### CODE REVIEW

**Comment by darkbasic** [comment]
```
> codelyzer@3.2.1 build:links /home/niko/WebstormProjects/deps/codelyzer
> ts-node build/links.ts --src ./dist

Error: Cannot find module '../../style-guide-links/all.json'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/niko/WebstormProjects/deps/codelyzer/build/links.ts:3:15)
    at Module._compile (module.js:612:30)
    at loader (/home/niko/WebstormProjects/deps/codelyzer/node_modules/ts-node/src/index.ts:290:14)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/niko/WebstormProjects/deps/codelyzer/node_modules/ts-node/src/index.ts:307:14)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
```

**Comment by darkbasic** [comment]
```
[niko@arch-desktop angularcli-graphql]$ git diff package.json 
diff --git a/package.json b/package.json
index 35e31f9..b41c1a6 100644
--- a/package.json
+++ b/package.json
@@ -12,27 +12,27 @@
   },
   "private": true,
   "dependencies": {
-    "@angular/animations": "^4.2.4",
-    "@angular/common": "^4.2.4",
-    "@angular/compiler": "^4.2.4",
-    "@angular/core": "^4.2.4",
-    "@angular/forms": "^4.2.4",
-    "@angular/http": "^4.2.4",
-    "@angular/platform-browser": "^4.2.4",
-    "@angular/platform-browser-dynamic": "^4.2.4",
-    "@angular/router": "^4.2.4",
+    "@angular/animations": "^5.0.0-rc.7",
+    "@angular/common": "^5.0.0-rc.7",
+    "@angular/compiler": "^5.0.0-rc.7",
+    "@angular/core": "^5.0.0-rc.7",
+    "@angular/forms": "^5.0.0-rc.7",
+    "@angular/http": "^5.0.0-rc.7",
+    "@angular/platform-browser": "^5.0.0-rc.7",
+    "@angular/platform-browser-dynamic": "^5.0.0-rc.7",
+    "@angular/router": "^5.0.0-rc.7",
     "core-js": "^2.4.1",
     "rxjs": "^5.4.2",
     "zone.js": "^0.8.14"
   },
   "devDependencies": {
     "@angular/cli": "1.5.0-rc.5",
-    "@angular/compiler-cli": "^4.2.4",
-    "@angular/language-service": "^4.2.4",
+    "@angular/compiler-cli": "^5.0.0-rc.7",
+    "@angular/language-service": "^5.0.0-rc.7",
     "@types/jasmine": "~2.5.53",
     "@types/jasminewd2": "~2.0.2",
     "@types/node": "~6.0.60",
-    "codelyzer": "~3.2.0",
+    "codelyzer": "file:../deps/codelyzer/codelyzer-3.2.1.tgz",
     "jasmine-core": "~2.6.2",
     "jasmine-spec-reporter": "~4.1.0",
     "karma": "~1.7.0",
@@ -44,6 +44,6 @@
     "protractor": "~5.1.2",
     "ts-node": "~3.2.0",
     "tslint": "~5.7.0",
-    "typescript": "~2.3.3"
+    "typescript": "~2.4.2"
   }
 }
[niko@arch-desktop angularcli-graphql]$ npm install
npm WARN codelyzer@3.2.1 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@3.2.1 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@3.2.1 requires a peer of @angular/platform-browser-dynamic@^2.3.1 || >=4.0.0-beta <6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@3.2.1 requires a peer of @angular/platform-browser@^2.3.1 || >=4.0.0-beta <6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@3.2.1 requires a peer of @angular/common@^2.3.1 || >=4.0.0-beta <6.0.0 but none is installed. You must install peer dependencies yourself.
```

Also, why do I get the following warnings despite using Angular 5.0.0-rc.7?

**Comment by mgechev** [comment]
@darkbasic removed one task, now you should be able to run `npm run release`.

**Comment by diagramatics** [comment]
I think you forgot to publish to npm?

**Comment by darkbasic** [comment]
Yes please publish the updated version.

**Comment by mgechev** [comment]
Not published yet, will do in this week.

**Pull request merged**
